require: rubocop-graphql

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/*/*'
    - 'config/initializers/*'

Style/Documentation:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Metrics/MethodLength:
  Max: 20
